# Generated by Django 3.1.1 on 2020-09-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200903_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='static/placeholder.png', null=True, upload_to='static'),
        ),
    ]
