# Generated by Django 3.1.1 on 2020-09-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200906_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/placeholder.png', upload_to='images'),
        ),
    ]
